services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /backend
    volumes:
      - ./backend:/backend
    ports:
      - "3030:3000"
    environment:
      PORT: 3030
      API_KEY: zGeaUH5zJWT2YCj0C8debpOnDMdS97qg
    networks:
      - my_network

  backend2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend2
    working_dir: /backend
    volumes:
      - ./backend:/backend
    ports:
      - "3031:3000"
    environment:
      PORT: 3031
      API_KEY: zGeaUH5zJWT2YCj0C8debpOnDMdS97qg
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - backend2
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules # Evita conflito entre host/container
    ports:
      - "3001:3000"
    environment:
      NUXT_LAMBDA_FUNCTION_SIGNUP: "http://nginx:8080/dev/signup"
      NUXT_LAMBDA_FUNCTION_CONFIRM_SIGNUP: "http://nginx:8080/dev/confirm-signup"
      NUXT_LAMBDA_FUNCTION_SIGNIN: "http://nginx:8080/dev/signin"
      NUXT_LAMBDA_FUNCTION_SIGNOUT: ""
      NUXT_LAMBDA_FUNCTION_UPLOAD: "http://nginx:8080/dev/upload"
      NUXT_LAMBDA_FUNCTION_CREATE_TRANSCRIPTION: "http://nginx:8080/dev/create-transcription"
      NUXT_LAMBDA_FUNCTION_GET_TRANSCRIPTIONS: "http://nginx:8080/dev/get-transcriptions"
      NUXT_SPEAECH_TO_TEXT_API_KEY: "zGeaUH5zJWT2YCj0C8debpOnDMdS97qg"
    networks:
      - my_network
    depends_on:
      - nginx

networks:
  my_network:
    driver: bridge
